/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme {
    extend: {
      colors: {
        'primary': '#0052ff',
        'primary-container': '#0052ff',
        'on-primary': '#ffffff',
        'primary-fixed': '#dde1ff',
        'primary-fixed-dim': '#b7c4ff',
        'on-primary-fixed': '#001452',
        'on-primary-fixed-variant': '#0038b6',
        'inverse-primary': '#b7c4ff',
        'surface': '#f7f9fb',
        'surface-dim': '#d8dadc',
        'surface-bright': '#f7f9fb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f6',
        'surface-container': '#eceef0',
        'surface-container-high': '#e6e8ea',
        'surface-container-highest': '#e0e3e5',
        'on-surface': '#191c1e',
        'on-surface-variant': '#434656',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eff1f3',
        'outline': '#737688',
        'outline-variant': '#c3c5d9',
        'secondary': '#515f74',
        'secondary-container': '#d2e1fa',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#556379',
        'tertiary': '#952200',
        'tertiary-container': '#bf3003',
        'on-tertiary': '#ffffff',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'background': '#f7f9fb',
        'on-background': '#191c1e',
      },
      spacing: {
        'gutter': '24px',
        'md': '16px',
        'margin-desktop': '64px',
        'xl': '32px',
        'margin-mobile': '24px',
        'max-width': '1440px',
        'xs': '4px',
        'lg': '24px',
        'sm': '8px',
        'xxl': '80px',
      },
      fontFamily: {
        'sans': ['Inter', 'sans-serif'],
        'mono': ['JetBrains Mono', 'monospace'],
        'headline': ['Inter', 'sans-serif'],
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      fontSize: {
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
